name: Publish RStudio Docker image
# To MaastrichtU-IDS GitHub Container Registry
# https://github.com/orgs/MaastrichtU-IDS/packages 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'Dockerfile'
    - '.github/workflows/publish-docker.yml'
  schedule:
    - cron: '0 3 * * 1'
    # Monday at 3:00 GMT+1

env:
  IMAGE_PUSHED: ghcr.io/maastrichtu-ids/rstudio:latest
  # BASE_IMAGE: rocker/verse:latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Log into GitHub Container Registry
      # # TODO: Create a token with `read:packages` and `write:packages` scopes 
      # # And save it as an Actions secret CONTAINER_REGISTRY_GITHUB_TOKEN
      #   run: echo "${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Build image
      #   run: docker build . --file Dockerfile --tag $IMAGE_PUSHED

      # - name: Push image to GitHub Container Registry
      #   run: |
      #     docker push $IMAGE_PUSHED


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CONTAINER_REGISTRY_GITHUB_TOKEN}}
          # password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and publish RStudio Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          # build-args: BASE_IMAGE=rocker/verse:latest
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.IMAGE_PUSHED }}
          cache-from: type=gha
          cache-to: type=gha,mode=max